jobs:
  job:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        SAMPLE_DIR: ${{ matrix.tf-sample }}
      name: terraform init & validate
      run: 'cd $SAMPLE_DIR

        terraform init -backend=false

        terraform validate

        '
    strategy:
      matrix:
        tf-sample:
        - iac/tf-anthos-gke
        - iac/tf-multienv-cicd-anthos-autopilot
name: tf-validate-ci
on:
  repository_dispatch:
    types: trigger-ga___terraform-validate-ci.yaml
